version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: accesorios_ph_db
    restart: always
    environment:
      POSTGRES_USER: ph_admin
      POSTGRES_PASSWORD: ph_secure_password_2026
      POSTGRES_DB: accesorios_ph
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
